# Generated by Django 5.2.4 on 2025-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='title',
            field=models.CharField(default='ttl', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.TextField(),
        ),
    ]
