# Generated by Django 5.2.4 on 2025-07-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postagem_title_alter_postagem_texto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postagem',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='text',
        ),
    ]
