# Generated by Django 5.2.4 on 2025-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_postagem_post_rename_texto_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='noimg.png', upload_to='images'),
        ),
    ]
